
---
title: "Chapter 3 - definitions of multimorbidity"
output: html_document
date: '2022-04-07'
---

## Load packages and plot settings
```{r setup, include=FALSE}
library(tidyverse)
library(ggrepel)
library(epitools)


theme_set(theme_minimal(base_size = 20) +
            theme(panel.grid.minor = element_blank(),
                  panel.grid.major = element_line(size = 0.25),
                  axis.line = element_line(colour = "black"),
                  axis.title.y = element_text(margin = margin(0, 20, 0, 0)),
                  axis.title.x = element_text(margin = margin(20, 0, 0, 0)),
                  plot.caption = element_text(colour = "#AAAAAA"),
                  plot.margin = margin(3, 15, 3, 3, "mm")))
```

## Max mm table

```{r}
base_table_max <- 
  read_csv("table_join_agegendIMD.csv",
           col_types = cols()) %>% 
  separate(age_gender_IMD, c("age", "gender", "IMD")) %>% 
  select(-gender, -IMD, -age)

table_max <- 
  base_table_max %>% 
  summarize(across(where(is.numeric),~sum(.x))) %>%
  pivot_longer(!n, names_to = "mm", values_to = "count") %>%
  rowwise %>%
  mutate(prop = ((prop.test(count, n, conf.level=0.95)$estimate)*100),
         lci = ((prop.test(count, n, conf.level=0.95)$conf.int[1])*100),
         uci = ((prop.test(count, n, conf.level=0.95)$conf.int[2])*100)) %>%
   mutate_if(is.numeric,
            round,
            digits = 2) %>%
  mutate(mm = as.integer(str_replace(mm, "mm_", "")))

write_csv(table_max, file="table_max.csv")

max_rrr <- table_max %>%
  select(mm, count) %>%
  rowwise %>%
  mutate(prop = ((prop.test(count, 473533, conf.level=0.95)$estimate)),
         lci = ((prop.test(count, 473533, conf.level=0.95)$conf.int[1])),
         uci = ((prop.test(count, 473533, conf.level=0.95)$conf.int[2]))) %>%
  mutate_if(is.numeric,
            round,
            digits = 2) %>%
  select(-count)

write_csv(max_rrr, file = "max_rrr.csv")
```

## Max mm plot

```{r, fig.width=12, fig.height=9}
ggplot(data=table_max, aes(x=mm, y=prop, group=1))+
  geom_line()+
  scale_y_continuous(limits= c(0, 45), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 2.5))) +
  scale_x_continuous(limits = c(0, 80), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 9.5))) +
  theme(legend.position = "top") +
  labs(x = "Number of conditions in the multimorbidity measure",
       y = "% with multimorbidity",
       #To remove legend title
       colour = "")+
  #To change legend labels
  scale_colour_grey(labels = c("Maximum multimorbidity", "Minimum multimorbidity"))

ggsave("max.pdf", width = 16, height = 12)
```

## Condition list table

```{r}
condlists_join <- read_csv("table_join_condlists.csv")

df <- read_csv("table_join_agegendIMD.csv") %>%
  select(age_gender_IMD, mm_80) %>%
  separate("age_gender_IMD", c("age", "gender", "IMD")) %>%
  mutate(age_IMD_gender = interaction(age, IMD, gender)) %>%
  select(age_IMD_gender, mm_80)

condlists_plot <- left_join(condlists_join, df, by = "age_IMD_gender") %>%
  replace(is.na(.),0) %>%
  separate(age_IMD_gender, c("age", "IMD", "gender")) %>%
  mutate(age = case_when(
    age == '00to04' | age == '05to09' ~ "0 - 9",
    age == '10to14' | age == '15to19' ~ "10 - 19",
    age == '20to24' | age == '25to29' ~ "20 - 29",
    age == '30to34' | age == '35to39' ~ "30 - 39",
    age == '40to44' | age == '45to49' ~ "40 - 49",
    age == '50to54' | age == '55to59' ~ "50 - 59",
    age == '60to64' | age == '65to69' ~ "60 - 69",
    age == '70to74' | age == '75to79' ~ "70 - 79",
    age == '80to84' | age == '85to89' | age == 'Over90' ~ "80+"
  )) %>% 
  select(age, always, always_usually, barnett, charlson, diederichs, elixhauser, fortin, salive, mm_80, n) %>%
  group_by(age) %>%
  summarize(across(where(is.numeric),~sum(.x))) %>%
  mutate('HDR-UK always (23 conditions)' = always/n *100,
         'HDR-UK always or usually (46 conditions)' = always_usually/n *100,
         'Barnett (33 conditions)' = barnett/n *100,
         'Charlson (15 conditions)' = charlson/n *100,
         'Diederichs (11 conditions)' = diederichs/n *100,
         'Elixhauser (22 conditions)' = elixhauser/n *100,
         'Fortin (20 conditions)' = fortin/n *100,
         'Salive (14 conditions)' = salive/n *100, 
         'All 80 conditions' = mm_80/n *100) %>%
 select(age, 'All 80 conditions', 'HDR-UK always or usually (46 conditions)', 'Fortin (20 conditions)', 'Barnett (33 conditions)', 'Salive (14 conditions)', 'Elixhauser (22 conditions)', 'Diederichs (11 conditions)', 'Charlson (15 conditions)', 'HDR-UK always (23 conditions)') %>%
  pivot_longer(!age, names_to = "mm", values_to = "prop") %>%                   # Using dplyr functions
  mutate_if(is.numeric,
            round,
            digits = 1)

condlists_plot$age <- factor(condlists_plot$age, levels = c('0 - 9', '10 - 19', '20 - 29','30 - 39', '40 - 49', '50 - 59', '60 - 69', '70 - 79', '80+'))

condlists_plot$mm <- factor(condlists_plot$mm, levels = c('All 80 conditions', 'HDR-UK always or usually (46 conditions)', 'Fortin (20 conditions)', 'Barnett (33 conditions)', 'Salive (14 conditions)', 'Elixhauser (22 conditions)', 'Diederichs (11 conditions)', 'Charlson (15 conditions)', 'HDR-UK always (23 conditions)'))
```

## Condition list plot (keeping ggrepel here to remember code)

```{r, fig.width=12, fig.height=9}
condlists_plot %>% 
  ggplot() +
  aes(age, prop, group = mm)+
  geom_line()+
  geom_text_repel(data=subset(condlists_plot, age == "80+"), aes(label = mm), 
                  size = 5, nudge_x = 1, nudge_y = 1.5,
                  direction = "y", segment.linetype = "dotted") +
  scale_y_continuous(limits= c(0, 100), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 2.5))) +
  scale_x_discrete(expand = expansion(add = c(0, 2.0))) +
  theme(legend.position = "none") +
  labs(x = "Age group (years)",
       y = "% with multimorbidity")

ggsave("age_xaxis_condlists.pdf", width = 16, height = 12)
```

## Age table

```{r}
base_table <- 
  read_csv("table_join_agegendIMD.csv",
           col_types = cols()) %>% 
  separate(age_gender_IMD, c("age", "gender", "IMD")) %>% 
  select(-gender, -IMD) %>%
  mutate(age = case_when(
    age == '00to04' | age == '05to09' ~ "0 - 9 years",
    age == '10to14' | age == '15to19' ~ "10 - 19 years",
    age == '20to24' | age == '25to29' ~ "20 - 29 years",
    age == '30to34' | age == '35to39' ~ "30 - 39 years",
    age == '40to44' | age == '45to49' ~ "40 - 49 years",
    age == '50to54' | age == '55to59' ~ "50 - 59 years",
    age == '60to64' | age == '65to69' ~ "60 - 69 years",
    age == '70to74' | age == '75to79' ~ "70 - 79 years",
    age == '80to84' | age == '85to89' | age == 'Over90' ~ "80+ years"
  ))

table_age <- 
  base_table %>% 
  group_by(age) %>%
  summarize(across(where(is.numeric),~sum(.x))) %>%
  pivot_longer(!age, names_to = "mm", values_to = "count") 

## Calculate denominator
df <- 
  base_table %>% 
  group_by(age) %>%
  summarize(SUMS = sum(n))

## Join denominator to main file, calculate proportion and factorise age
age_plot <- 
  left_join(table_age, df, by = "age") %>%
  filter(!mm == "n") %>% 
  mutate(prop = count/SUMS * 100,
         age = factor(age, 
                      levels = c('80+ years', '70 - 79 years', '60 - 69 years',
                                 '50 - 59 years', '40 - 49 years', 
                                 '30 - 39 years', '20 - 29 years', 
                                 '10 - 19 years', '0 - 9 years')),
         mm = str_replace(mm, "mm_", "") %>% 
           as.integer()) %>% 
  select(-SUMS) 

## Calculate RRR table
## Table including maximum mm % for each age group
df2 <- age_plot %>%
  filter(mm == "80") %>%
  select(-prop) %>%
  rename(rr_80 = count)

rrr_count <- age_plot %>%
  select(age, mm, count)

age_rrr <- 
  left_join(rrr_count, df2, by ="age") %>%
  select(-mm.y) %>%
  rowwise %>%
   mutate(prop = ((prop.test(count, rr_80, conf.level=0.95)$estimate)),
         lci = ((prop.test(count, rr_80, conf.level=0.95)$conf.int[1])),
         uci = ((prop.test(count, rr_80, conf.level=0.95)$conf.int[2]))) %>%
  mutate_if(is.numeric,
            round,
            digits = 2)

write_csv(age_rrr, file = "age_rrr.csv")
```

## Age stratified plot

```{r, fig.width=16, fig.height=12}
age_plot %>% 
  ggplot() +
  aes(mm, prop, group = age, colour = age)+
  geom_line()+
  scale_y_continuous(limits= c(0, 100), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 2.5))) +
  scale_x_continuous(limits = c(0, 80), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 9.5))) +
  #theme(legend.position = "none") +
  labs(x = "Number of conditions considered in the count",
       y = "% of each IMD-decile with multimorbidity")
  
ggsave("age_stratified.pdf", width = 16, height = 12)
```

## IMD table

```{r}
base_table <- 
  read_csv("table_join_agegendIMD.csv",
           col_types = cols()) %>% 
  separate(age_gender_IMD, c("age", "gender", "IMD")) %>% 
  select(-gender)

table_IMD <- base_table %>%
  pivot_longer(starts_with("mm"), names_to = "mm", values_to = "count") %>%
  group_by(age) %>%
  mutate(standard = mean(n)) %>%
  group_by(mm, IMD) %>%
  summarise(ageadj = list(round(ageadjust.direct(count, n, stdpop = standard)*10^2, 2))) %>%
  unnest_wider(ageadj)

## Calculate denominator
df <- 
  base_table %>% 
  group_by(IMD) %>%
  summarize(SUMS = sum(n))

## Join denominator to main file, calculate proportion of RRR
IMD_plot <- 
  left_join(table_IMD, df, by = "IMD") %>%
         mutate(mm = str_replace(mm, "mm_", "")) %>% 
  select(-SUMS) 

df2 <- IMD_plot %>%
  filter(mm == "80") %>%
  dplyr::select(IMD, adj.rate) %>%
  rename(rr_80 = adj.rate)

IMD_rrr <- 
  left_join(IMD_plot, df2, by ="IMD") %>%
  select(-mm.y) %>%
  mutate(rrr = adj.rate/rr_80) %>%
  mutate_if(is.numeric,
            round,
            digits = 2) %>%
  select(mm.x, IMD, rrr)

write_csv(IMD_rrr, file = "rrr_IMD_table.csv")

IMD_plot$mm <- as.integer(IMD_plot$mm)
```

## Plot

```{r, fig.width=16, fig.height=12}
IMD_plot %>% 
  ggplot() +
  aes(mm, adj.rate, group = IMD, colour = IMD)+
  geom_line()+
  #geom_errorbar(aes(ymin = lci, ymax = uci)) +
  scale_y_continuous(limits= c(0, 50), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 2.5))) +
  scale_x_continuous(limits = c(0, 80), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 9.5))) +
 #theme(legend.position = "none") +
  labs(x = "Number of conditions considered in the count",
       y = "% of each IMD-decile with multimorbidity")
  
ggsave("IMD_stratified.pdf", width = 16, height = 12)
```

## Sex table

```{r}
base_table <- 
  read_csv("table_join_agegendIMD.csv",
           col_types = cols()) %>% 
  separate(age_gender_IMD, c("age", "gender", "IMD")) %>% 
  select(-IMD)

table_gender <- base_table %>%
  pivot_longer(starts_with("mm"), names_to = "mm", values_to = "count") %>%
  group_by(age) %>%
  mutate(standard = mean(n)) %>%
  group_by(mm, gender) %>%
  summarise(ageadj = list(round(ageadjust.direct(count, n, stdpop = standard)*10^2, 2))) %>%
  unnest_wider(ageadj)

## Calculate denominator
df <- 
  base_table %>% 
  group_by(gender) %>%
  summarize(SUMS = sum(n))

## Join denominator to main file, calculate proportion and factorise age
gender_plot <- 
  left_join(table_gender, df, by = "gender") %>%
         mutate(mm = str_replace(mm, "mm_", "")) %>% 
  select(-SUMS) 

df2 <- gender_plot %>%
  filter(mm == "80") %>%
  dplyr::select(gender, adj.rate) %>%
  rename(rr_80 = adj.rate)

gender_rrr <- 
  left_join(gender_plot, df2, by ="gender") %>%
  select(-mm.y) %>%
  mutate(rrr = adj.rate/rr_80) %>%
  mutate_if(is.numeric,
            round,
            digits = 2) %>%
  select(mm.x, gender, rrr)

write_csv(gender_rrr, file = "rrr_gender_table.csv")

gender_plot$mm <- as.integer(gender_plot$mm)
```

## Sex plot

```{r, fig.width=16, fig.height=12}
gender_plot %>% 
  ggplot() +
  aes(mm, adj.rate, group = gender, colour = gender)+
  geom_line() +
  #geom_errorbar(aes(ymin = lci, ymax = uci)) +
  scale_y_continuous(limits= c(0, 50), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 2.5))) +
  scale_x_continuous(limits = c(0, 80), 
                     breaks = scales::pretty_breaks(n = 10),
                     expand = expansion(add = c(0, 9.5))) +
 #theme(legend.position = "none") +
  labs(x = "Number of conditions considered in the count",
       y = "% of each IMD-decile with multimorbidity")

ggsave("gender_stratified.pdf", width = 16, height = 12)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.